#!/usr/bin/python3
""" Factor numbers """
import sys


def factorize(num):
    for i in range(2, int(num ** 0.5) + 1):
        if num % i == 0:
            return i, num // i
    return None, None


if __name__ == '__main__':
    if len(sys.argv) != 2:
        print('Usage: factors <file>')
        exit(1)

    try:
        with open(sys.argv[1], 'r') as f:
            for line in f:
                num = int(line.strip())
                p, q = factorize(num)
                if p is None:
                    print(f"{num} is a prime number")
                else:
                    print(f"{num}={p}*{q}")
    except FileNotFoundError:
        print(f"Error: {sys.argv[1]} not found")
        exit(1)
