#!/usr/bin/python3
import sympy
import sys


if __name__ == '__main__':
    if len(sys.argv) != 2:
        print('Usage: factors <file>')
        exit(1)

    try:
        with open(sys.argv[1], 'r') as f:
            for line in f:
                n = int(line.strip())
                factors = sympy.factorint(n)
                print(f"{n} = " + " * ".join([f"{p}^{factors[p]}" for p in factors]))
    except FileNotFoundError:
        print(f"Error: {sys.argv[1]} not found")
        exit(1)

